<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
		<meta charset="utf-8">

		<script>
			dojoConfig = {
				parseOnLoad: true,
				gfxRenderer: "svg,silverlight,vml",
				isDebug: true
			};
		</script>
        <script src="./dojo-release-1.7.1/dojo/dojo.js"></script>
		<script>
        	dojo.require("dojox.gfx");
        	dojo.require("dojox.gfx.Moveable");
			dojo.require("dojox.gfx.fx");

			var Agents = Array();

			function MoveAgents()
			{
				dojo.forEach(Agents, 
					function(Agent, index)
					{
						Agent.applyTransform(dojox.gfx.matrix.translate(0, index/10));
					}
				);
			}
		
			dojo.ready(function()
			{
				var surface = dojox.gfx.createSurface("surfaceElement",2000,000);
				var group = surface.createGroup();
				
				function CreateAgent(x, y)
				{
					var Agent = group.createCircle({cx: x, cy: y, r: 100});
					Agent.setFill({
					    type: "radial",
					    cx: x+20,
					    cy: y-20,
					    colors:
						[
					        { offset: 0,   color: "#4ea1fc" },
					        { offset: 0.5, color: "#0072e5" },
					        { offset: 1,   color: "#003b80" }
						]
					});
					return Agent;
				}			
<?php
for ($i=0; $i<1000; $i++)
{
	echo "Agents[$i]=CreateAgent(".($i*100 + 100).",100);";						
}
?>

				group.applyTransform(dojox.gfx.matrix.scale(0.02, 0.02));
				
				new dojox.gfx.Moveable(group);

				setInterval('MoveAgents();', 1);
			});
		</script>
    </head>
    <body>
		<div id="surfaceElement" style="border:1px solid #ccc;width:2000px;height:1000px;"></div>
    </body>
</html>